### ISSUE TITLE
RAND_egd?

### ISSUE THREAD

**Issue by Jay4242** [blueturtleai/gimp-stable-diffusion#10]
I get the following error,

```
Traceback (most recent call last):
  File "/home/USERNAME/.config/GIMP/2.10/plug-ins/gimp-stable-diffusion-horde.py", line 5, in <module>
    import urllib2
  File "/usr/lib/python2.7/urllib2.py", line 94, in <module>
    import httplib
  File "/usr/lib/python2.7/httplib.py", line 72, in <module>
    import socket
  File "/usr/lib/python2.7/socket.py", line 68, in <module>
    from _ssl import \
ImportError: cannot import name RAND_egd

```
When the horde script is in my ~/.config/GIMP/2.10/plug-ins/ and running https://github.com/TasMania17/Gimp-Appimages-Made-From-Debs/releases/tag/Gimp-Python2-AppImage-Launchers-for-Linux

**Comment by blueturtleai** [comment]
Could you please try to install this version? https://flathub.org/apps/details/org.gimp.GIMP

And please also check the troubleshooting section in the readme.

**Comment by Jay4242** [comment]
OK, the flatpak worked.  Great, thanks.  Idk why that was my last resort.  Is that mentioned in the readme?

**Comment by blueturtleai** [comment]
Great, that it works now! Yes, it is mentioned in the readme.
